apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpakoper
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cpakoper
  template:
    metadata:
      labels:
        name: cpakoper
    spec:
      serviceAccountName: cpakoper
      containers:
        - name: cpakoper
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - cpakoper
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cpakoper"
