// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CpakOper) DeepCopyInto(out *CpakOper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CpakOper.
func (in *CpakOper) DeepCopy() *CpakOper {
	if in == nil {
		return nil
	}
	out := new(CpakOper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CpakOper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CpakOperList) DeepCopyInto(out *CpakOperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CpakOper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CpakOperList.
func (in *CpakOperList) DeepCopy() *CpakOperList {
	if in == nil {
		return nil
	}
	out := new(CpakOperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CpakOperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CpakOperSpec) DeepCopyInto(out *CpakOperSpec) {
	*out = *in
	if in.CPFeatures != nil {
		in, out := &in.CPFeatures, &out.CPFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CpakOperSpec.
func (in *CpakOperSpec) DeepCopy() *CpakOperSpec {
	if in == nil {
		return nil
	}
	out := new(CpakOperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CpakOperStatus) DeepCopyInto(out *CpakOperStatus) {
	*out = *in
	if in.InstalledFeatures != nil {
		in, out := &in.InstalledFeatures, &out.InstalledFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CpakOperStatus.
func (in *CpakOperStatus) DeepCopy() *CpakOperStatus {
	if in == nil {
		return nil
	}
	out := new(CpakOperStatus)
	in.DeepCopyInto(out)
	return out
}
